# Generated by Django 2.2.2 on 2020-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_equipmenttemplatemqtt'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyTemplateMQTTInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('apply_mqtt_template', models.CharField(max_length=30, verbose_name='应用mqtt接口模板名称')),
                ('apply_mqtt_device', models.CharField(max_length=30, verbose_name='应用mqtt接口设备名称')),
                ('apply_mqtt_ip', models.CharField(max_length=30, verbose_name='应用mqtt接口IP地址')),
                ('apply_mqtt_port', models.CharField(max_length=30, verbose_name='应用mqtt接口端口号')),
                ('apply_mqtt_userName', models.CharField(max_length=30, verbose_name='应用mqtt接口连接用户名')),
                ('apply_mqtt_pwd', models.CharField(max_length=30, verbose_name='应用mqtt接口连接密码')),
                ('apply_mqtt_topic', models.CharField(max_length=30, verbose_name='应用mqtt接口訂閱主題')),
                ('apply_mqtt_drive', models.CharField(max_length=30, verbose_name='应用mqtt接口绑定的驱动名称')),
                ('apply_mqtt_active', models.BooleanField(default=True, verbose_name='应用mqtt接口是否启动')),
            ],
            options={
                'verbose_name': '应用mqtt设备模板库记录',
                'db_table': 'gateway_apply_template_mqtt_interface',
                'verbose_name_plural': '应用mqtt设备模板库记录',
            },
        ),
    ]
