# Generated by Django 2.2.2 on 2020-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0007_applytemplatemqttinterface'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='path',
            table='gateway_path_list',
        ),
    ]
