# Generated by Django 2.2.2 on 2020-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_settingdown_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('down_type', models.CharField(max_length=30, verbose_name='配置的类型')),
                ('down_topic', models.CharField(max_length=30, verbose_name='主题')),
                ('down_num', models.CharField(max_length=30, verbose_name='已下发次数')),
                ('down_param', models.CharField(max_length=300, verbose_name='需要的参数设置')),
                ('down_remark', models.CharField(max_length=100, verbose_name='下发描述')),
            ],
            options={
                'verbose_name_plural': '網關配置下发',
                'db_table': 'gateway_settingdown',
                'verbose_name': '網關配置下发',
            },
        ),
    ]
