# Generated by Django 2.2.2 on 2020-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotely', '0002_get_settingdown_model_down_num2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_settingdown_model',
            name='down_num',
            field=models.IntegerField(default=0, verbose_name='已下发次数'),
        ),
        migrations.AlterField(
            model_name='get_settingdown_model',
            name='down_num2',
            field=models.IntegerField(default=0, verbose_name='失敗次數'),
        ),
    ]
