# Generated by Django 2.2.2 on 2020-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_event_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('event_level', models.CharField(max_length=30, verbose_name='事件等級')),
                ('event_username', models.CharField(max_length=30, verbose_name='用戶操作')),
                ('event_remark', models.CharField(max_length=100, verbose_name='事件詳情')),
            ],
            options={
                'verbose_name_plural': '網關事件中心',
                'verbose_name': '網關事件中心',
                'db_table': 'gateway_event',
            },
        ),
    ]
