# Generated by Django 2.2.2 on 2020-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartDevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('smart_sname', models.CharField(max_length=30, unique=True, verbose_name='智能产品SN名称')),
                ('smart_sns', models.CharField(max_length=50, verbose_name='智能产品SN')),
            ],
            options={
                'verbose_name': '网关智能产品SN信息',
                'db_table': 'gateway_smartsns_list',
                'verbose_name_plural': '网关智能产品SN信息',
            },
        ),
        migrations.AlterField(
            model_name='smartcommunicate',
            name='smart_enable',
            field=models.BooleanField(default=False, verbose_name='通信路径激活使能'),
        ),
    ]
