# Generated by Django 2.2.2 on 2020-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_auto_20200427_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTemplateMqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('etm_name', models.CharField(max_length=30, verbose_name='模板名称')),
                ('etm_remark', models.CharField(max_length=30, verbose_name='模板描述')),
                ('etm_accordname', models.CharField(default='MQTT', max_length=30, verbose_name='模板协议名称')),
                ('etm_param', models.CharField(max_length=30, verbose_name='字段名稱')),
                ('etm_param_as', models.CharField(max_length=30, verbose_name='字段別名')),
                ('etm_type', models.CharField(max_length=30, verbose_name='字段類型')),
                ('etm_null', models.CharField(max_length=30, verbose_name='字段是否為空')),
            ],
            options={
                'verbose_name': 'MQTT採集傳輸设备模板库',
                'verbose_name_plural': 'MQTT採集傳輸设备模板库',
                'db_table': 'gateway_equipmenttemplatemqtt',
            },
        ),
    ]
